### PR TITLE
Switching the oss-cad-suites to the 'opt out' appraoch

### PR DESCRIPTION
**Pull request by zapta**
@Obijuan, @cavearr, after this PR is going in, please create a new release ``v0.2.0`` with 5 release packages files for the 5 supported platforms.  You can build the 5 release files using the shell script below or copy them from here https://github.com/zapta/tools-oss-cad-suite/releases/tag/v0.2.0

PR Description

This PR changes the way we build the apio's opt-cad-suites from the 'opt-in' approach, where select the files we thing are needed, the the 'opt-out' approach where we select all the upstream files and add/remove/delete files only if we must to. This approach has a few advantages:

1. More confidence that all the files we need are included.
2. Access to all features of the oss-cad suite.
3. More confidence when submitting upstream issues to the yosys team that we didn't cause the issue.
4. Easier to upgrade to future version of oss-cad-suite.

Once this will be in, with a new v0.2.0 release, I will submit a followup PR that adapts apio to the new model.

Bash script to build the release files:

```sh
#!/bin/bash

set -e

rm -rf _upstream _packages VERSION_BUILD

./build.sh    linux_x86_64
./build.sh    linux_aarch64
./build.sh    darwin
./build.sh    darwin_arm64
./build.sh    windows_amd64

echo
ls -al _upstream/*/oss-cad-suite-*
echo
ls -l -d  _packages/tools-*
```

### CODE REVIEW

**Comment by cavearr** [comment]
Hi @zapta, @Obijuan should check this before release build. He is using Apio at University classes and I don't know if this version could cause some problems because it is not tested enough.

I think it should be reviewed well.

To use it from icestudio wip with apio develop, it seems perfect to me, i'm waiting for your decision, team!

**Comment by cavearr** [comment]
Go ahead! i play with it!

**Comment by zapta** [comment]
Thanks @cavearr!

I need release 0.2.0 with the release files to test. Any news on the evaluation?

(My understanding is that as long as we don't change the file VERSION and release 0.0.9, prod will not be affected.)

**Comment by cavearr** [comment]
hi @zapta ,i'm waiting @Obijuan do it, but if he don't do in a few hours, i'll do it ok?

Thanks!

**Comment by zapta** [comment]
Thanks Carlos!

Once you set it up, you can try to uninstall and reinstall the
oss-cad-suite package on a prod apio and verify that it loads 0.0.9 and not
0.2.0.

**Comment by cavearr** [comment]
Hi @zapta,  @Obijuan launch the release but is broken because we have no left space in github actions to complete it.

I'm working on it, researching how to fix it, could be a real problem, but i try to solve it and adapt the action to this new envieronment.

**Pull request merged**
